### ISSUE TITLE
Code Merge Issue

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/librarymangementsytem-core#2]
There is code merge issue.  Check all classes

![image](https://user-images.githubusercontent.com/22638364/126302748-d07a23a5-c495-44d3-8291-cfcaee16e503.png)

![image](https://user-images.githubusercontent.com/22638364/126302858-3db17518-cfde-4681-b7c4-9eddc3308135.png)

![image](https://user-images.githubusercontent.com/22638364/126302959-184eca3f-f0a1-4543-8af1-9263d178b633.png)

**Comment by Nevilston** [comment]
Cleared the issue and re-uploaded sir
